# Generated by Django 4.1.7 on 2023-05-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
